name: Update README

on:
  push:
    branches:
      - update-readme-test

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Get current release
        run: |
          currentRelease="$(git describe --tags --abbrev=0)"
          echo 'CURRENT_RELEASE='$currentRelease >> $GITHUB_ENV
      
      - name: Update README
        run: |
          sed -i "s/\/releases\/download\/.*\//\/releases\/download\/$CURRENT_RELEASE\//" README.md

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update README with latest release"
          git checkout -b update-readme
          git push origin update-readme

      - name: Create pull request
        run: |
          gh pr create --base main --head update-readme --title "Update README with latest release" --body "This PR updates the README with the latest release."
          gh pr merge --auto --squash --delete-branch --rebase update-readme