name: Update README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Update-README:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current release
        run: |
          currentRelease="$(gh release list --limit 1 --json name | jq -r '.[0].name')"
          echo 'CURRENT_RELEASE='$currentRelease >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update README with latest release
        run: |
          sed -i "s/\/releases\/download\/.*\//\/releases\/download\/$CURRENT_RELEASE\//" README.md

      - name: Commit changes and create PR
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b update-readme
          git add README.md
          git commit -m "Update README with latest release"
          git push origin update-readme
          gh pr create --base main --head update-readme --title "Update README with latest release" --body "This PR updates the README with the latest release."
          gh pr merge update-readme --auto --squash --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}